### ISSUE TITLE
AppMaps should be indexed without requiring a restart of the IDE in JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#125]
Found on both Linux and Windows.

Currently, indexing of the AppMaps only works if you restart the IDE.

To reproduce:

1. Install extension
2. `git clone https://github.com/land-of-apps/sample_app_6th_ed.git`
3. Switch to `codespaces-devcontainer` branch
4. Make sure you're using Node 14
5. `bundle install`
6. `yarn install --check-files`
7. `rails db:migrate`
8. `rails test` (to make sure it's working)
9. `rake db:seed`
10. Open project picker and use installer command
11. Open `Record AppMaps` page and use default command

AppMaps will appear but won't be indexed. If you restart the IDE the AppMaps will get indexed.

**Comment by jansorg** [comment]
Sometimes the scanner doesn't detect new files on disk and perhaps the IDE isn't picking up appmap-findings.json files properly.
Do you remember if `appmap-findings.json` files were generated by index+scanner or not?

**Comment by ahtrotta** [comment]
Indexing appears to be working correctly now
