### ISSUE TITLE
Code Objects view should exist

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#127]
This should match what the VS Code extension supports, with a section of the panel dedicated to users browsing the catalog of indexed objects found in all the maps:

![Image](https://user-images.githubusercontent.com/573108/190864239-70498865-fca9-41a8-860f-16f0a573e6ec.png)

**Comment by ahtrotta** [comment]
@jansorg here is a spec: https://docs.google.com/document/d/14kVc7C-7ZSITcVEk6skmXthLtNyR0lxVRrL_bc-EL1U/edit

Please let me know if you need anything isn't clear!
