### ISSUE TITLE
Findings associated with an unknown file open the associated AppMap

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-intellij-plugin#143]
Upon clicking the finding below, nothing occurs

![Image](https://user-images.githubusercontent.com/8737782/194097816-dc481aba-689d-4c8e-967f-65281b0bced4.png)

The data referenced is attached: [Microposts_controller_can_get_microposts_as_JSON.zip](https://github.com/getappmap/appmap-intellij-plugin/files/9716908/Microposts_controller_can_get_microposts_as_JSON.zip)

**Comment by jansorg** [comment]
What should have happened?
Clicking on findings with known source files opens the source file. In this case we only could open the AppMap, I guess.

**Comment by jansorg** [comment]
@ahtrotta I think you offered to provide a spec. Is the document already available?

**Comment by ahtrotta** [comment]
Thanks for the reminder! I'll get that to you soon.

**Comment by ahtrotta** [comment]
Hi @jansorg, [here](https://docs.google.com/document/d/1a9eWDO6hxt_xx4DKQInUIpr_RDmbAjgLhqU8_5LRONw/edit) is the spec. Let me know if you have any questions!
