### ISSUE TITLE
AppMaps from remote recordings should be stored in `tmp/appmap` by default instead of the project's root directory

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#146]
When stopping a remote recording in intellij, the prompt for saving the appmap suggests saving in the root directory:

![Image](https://user-images.githubusercontent.com/45714532/195705531-67edd51a-7ef8-4e67-aed3-cfa47d83116b.png)

Instead, it should suggest saving it in the `tmp/appmap` directory:

![Image](https://user-images.githubusercontent.com/45714532/195705661-4a329fff-481b-414f-988e-7045dfdaa785.png)

**Comment by jansorg** [comment]
Remarks by the team:
- The first choice is to use the `appmap_dir` from the `appmap.yml` file
- Second choice is `tmp/appmap`
- In either case, create or use the subdirectory “remote”
