### ISSUE TITLE
AppMaps should be scanned without requiring a restart of the IDE in JetBrains

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#147]
Tested in IntelliJ Community on Linux (Ubuntu)

If I generate an AppMap from a remote recording (for example, in Spring Pet Clinic), then I get indexing of that appmap and I get all of these expected files:

![Image](https://user-images.githubusercontent.com/45714532/195707017-08e04405-7984-4208-89e1-70bef957516d.png)

But I'm not getting `appmap-findings.json` until I restart the IDE:

![Image](https://user-images.githubusercontent.com/45714532/195707198-e12eb573-4be9-4d01-9b88-4bedebeeee30.png)

**Comment by jansorg** [comment]
The plugin is not creating appmap-findings.json, but the CLI tools are.
The plugin restarts the CLI processes when a project is opened and terminates them when it's closed.
Does this happen in VSCode, too?

**Comment by ahtrotta** [comment]
I just tested VS Code in Linux and I did not have this issue. So it may be related to how the scanner is getting launched in JetBrains.

**Comment by jansorg** [comment]
I'm not able to reproduce anymore with the latest CLIs.

**Comment by ahtrotta** [comment]
I couldn't reproduce this with the latest CLIs, either.
