### ISSUE TITLE
JetBrains generates OpenAPI specs

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#163]
Matching what the VS Code plugin does, the JetBrains plugin should also allow any user with maps to generate OpenAPI specs from within the editor.

In VS Code, this feature appears in 2 places:
1. As the 4th "project picker" step
![Image](https://user-images.githubusercontent.com/573108/201750876-84f34c08-d5f6-4ee2-970a-ca1744958645.png)

2. As a special in-editor command 
![Image](https://user-images.githubusercontent.com/573108/201750967-bbc5654c-2c1c-4d82-b804-49a5c39d26c8.png)
Since JetBrains doesn't have a similar context menu as in 2), we should just offer 1) for now.

Once the user clicks the button to generate OpenAPI specs, it should run the command to do so in the background (it works very quickly) and then open the newly-generated OpenAPI file within the IDE.

**Comment by dustinbyrne** [comment]
To generate OpenAPI definitions, the following command is executed:
```sh
$ appmap openapi --appmap-dir ${workspaceDirectory}
```

If more than one workspace directory is available, the user must first choose which directory to generate OpenAPI definitions with.

The OpenAPI definitions are emit to `stdout` as a YAML document.

If the user clicked the `Generate OpenAPI definitions` button from the instructions view, a new editor window will split open to the right of the instructions containing the YAML document. If the user is generating OpenAPI from anywhere else (e.g. the command palette), the document will open as a new editor window in the main editor area (without splitting).

The OpenAPI page will need to be enabled by removing it from the disabled pages
https://github.com/getappmap/appmap-intellij-plugin/blob/dba365620b0704da26151f0ab42c7087bad85cec/plugin-core/src/main/java/appland/installGuide/InstallGuideEditor.java#L323-L324

When the user clicks the generate button, a `generate-openapi` event is emitted from the webview. It looks like it's already being forwarded to the plugin backend:
https://github.com/getappmap/appmap-intellij-plugin/blob/dba365620b0704da26151f0ab42c7087bad85cec/appland-install-guide/installGuideView.js#L98-L100

Upon generating OpenAPI definitions, an `open_api:generate` telemetry event is sent. It contains a single property (which we'll say is optional for now if it's a significant effort), `appmap.project.language` which indicates the primary language of the project (`java`, `ruby`, `python`, `javascript`, `unknown`).

**Comment by kgilpin** [comment]
There’s also a command option to direct the output to a file, if you’d
prefer that.

**Comment by jansorg** [comment]
@dustinbyrne AFAIK VSCode generates a temporary files, which isn't saved to disk. In IntelliJ there are in-memory files, but these can't be saved to disk (due to a differenct concept of file handling). 
Would you prefer to create a new OpenAPI file in the select project root or an in-memory file?

**Comment by dustinbyrne** [comment]
I think it makes the most sense to write it to a file on disk in that case.
