### ISSUE TITLE
JetBrains displays Runtime Analysis finding pages

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#174]
Subtasks:
- [ ] "Runtime Analysis" panel
- [ ] New JS application for the two new web views
- [ ] Navigation support between the two

**Comment by Daniel-Warner-X** [comment]
Demo Video of feature in VS Code:

https://appmap-io.zoom.us/rec/share/lBo4ME8KFPu1-lqsVLB4DMQlVpZdzTdUyp_i_eJ_spQwP48rerZ-KvHa2lvZ7Y_e.Y8HXf-Abd_UeX54m (Passcode: 0176M=qx)
