### ISSUE TITLE
JetBrains requires sign-in for usage

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#232]
@ahtrotta to add details on what the UX should be in order to match the VS Code flow.

**Comment by ahtrotta** [comment]
Here is the [spec](https://docs.google.com/document/d/1KGnRJ3LaOeekNCn6-Ia2IoudBQVr4PtEwIPZ9A_Ba7k/edit?usp=sharing).

Please let me know if anything is unclear.

**Comment by ahtrotta** [comment]
@brikelly, are we putting this on hold?

**Comment by brikelly** [comment]
No, @Daniel-Warner-X is creating a new design for the page, but we still need to build the plumbing to render it. So for now we'll proceed to get this prepared, and drop in the UI changes from Dan once they're ready.

**Comment by jansorg** [comment]
@ahtrotta Is this component already available via NPM? https://github.com/getappmap/appmap-js/commit/5c18782dccae16a61a121aefa199d87697448d27#diff-8f0db08fec54128a50fad8a9e12c6afc7451d85716eac2a988afda5d16345dd5R1

**Comment by ahtrotta** [comment]
Yes, that should be available

**Comment by jansorg** [comment]
Thanks! I was able to import it after updating to the latest appmap/components.
