### ISSUE TITLE
IntelliJ crashes when trying to open an AppMap after dragging it into a project. 

### ISSUE THREAD

**Issue by ghamelin** [getappmap/appmap-intellij-plugin#259]
IntelliJ crashes completely after trying to open an AppMap that was dragged and dropped into the project. After crashing and upon reopening IntelliJ the AppMap Icon in the right menu bar completely disappeared.

**Comment by jansorg** [comment]
I wasn't able to reproduce this on Linux with a 21mb and a 42mb AppMap.
Which OS, IDE and IDE version did you use when this happened?

After a crash happened, please restart the IDE and attach or send the log file opened by `Help > Show Log in ...`.

If the AppMap icon is missing, then the IDE perhaps disabled the faulty plugin. You should be able to re-enable or reinstall at `Preferences > Settings > Plugins > Installed`.

**Comment by tokazio** [comment]
I'm on the last IJ of 2022 on M1 Mac Book pro.
In my case it's not crashing, it not handle the file drop or open it as a json insteadof opening the diagram

**Comment by jansorg** [comment]
We were unable to reproduct this, but we've applied a possible fix/workaround in the recent updates. Please open a new issue with logs attached if you're experiencing this again.
