### ISSUE TITLE
Update the plugin description

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-intellij-plugin#263]
This link should be removed entirely:
https://github.com/getappmap/appmap-intellij-plugin/blob/0877f558015d8c9c2dd0a7d0e73f53e585dbb161/description.md?plain=1#L7

And the live plugin description updated @ https://plugins.jetbrains.com/plugin/16701-appmap

**Comment by ahtrotta** [comment]
Once the JetBrains plugin is approved, we can archive this.
