### ISSUE TITLE
Maps from sibling folders show up in the JetBrains map list

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#267]
@kgilpin can reproduce this, and reports that when he has a project open in folder A, he can also see maps from sibling folder B. This could cause significant problems for the plugin as it tries to watch / index too many files, and also create a confusing UX.

Unknown how to reliably reproduce this on other systems yet.

Maybe there is an `appmap.yml` in a parent folder outside the workspace. But even in that case, `appmap_dir` should be respected. Generally speaking, only valid appmap_dir should be considered when listing or indexing AppMaps.

**Comment by jansorg** [comment]
> Maybe there is an `appmap.yml` in a parent folder outside the workspace. But even in that case, `appmap_dir` should be respected. Generally speaking, only valid appmap_dir should be considered when listing or indexing AppMaps.

 @brikelly Could you clarify the expcted behavior? Currently, only AppMap files found in the current project's directories are shown. But these files are currently not filtered by the `appmap_dir` values of appmap.yml config files.

**Comment by dividedmind** [comment]
@ahtrotta you moved this to *In Review* but there is no pull request attached?

**Comment by jansorg** [comment]
@dividedmind Sorry, my bad. I added https://github.com/getappmap/appmap-intellij-plugin/pull/295
