### ISSUE TITLE
Class map item type "external-route" should be supported

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#272]
See https://github.com/getappmap/appmap-intellij-plugin/issues/271 for a bug, where this unknown type triggered an exception

**Comment by dividedmind** [comment]
Isn't this done?

**Comment by jansorg** [comment]
Nope, the previous fix made sure that unknown properties are not breaking the IDE's indexing.
But the property is still not displayed in the UI, because I wasn't sure what should be done with the code objects of this type.

**Comment by dustinbyrne** [comment]
Here's an example AppMap containing an external service.

[external_service_example.appmap.json.txt](https://github.com/getappmap/appmap-intellij-plugin/files/12173902/external_service_example.appmap.json.txt)

**Comment by jansorg** [comment]
@dustinbyrne Can you tell if/how VSCode is showing external-service and external-route? I don't see items for these types with the AppMap above.

**Comment by jansorg** [comment]
It turned out that in VSCode external services are only displayed in the AppMap webview. We're already using the current version and thus also display the external services.
