### ISSUE TITLE
User can save filter settings and change the default filter

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#283]

**Comment by jansorg** [comment]
@ahtrotta Could you add a few details to help me understand what needs to be done? For example, I'm not sure which filter this is about.

**Comment by brikelly** [comment]
@jansorg This was a new feature added to VS Code which is now released on that marketplace. There are some details here: https://github.com/getappmap/appmap-js/pull/1186

We are also creating a video to announce this feature so we can share that soon. It will demonstrate the behaviors and usage. Most of the work was done in appmap-js and already released, but the JetBrains plugin will need to add code to save filter settings appropriately.

**Comment by ahtrotta** [comment]
@jansorg [here](https://docs.google.com/document/d/10uG5AtfYQst0Q-hq_hcT8yEzjk7qSZMeRC28bzeIiYA/edit) is a spec for this feature. Let me know if you have any questions!

**Comment by jansorg** [comment]
@ahtrotta Would it be possible to keep `AppMapFilter` out of the frontend? As far as I understand, atm the frontend needs to know about the structure of `AppMapFilter` only to create the Base64 encoded state of the default filter. I can't import `AppMapFilter` as VSCode, but would have to copy (and keep in sync) the properties of this type (`rootObjects, `declutter` with all sub-properties).
IMHO the webview itself should init the default filter and just tell the host (i.e. the plugin) when it should be saved or updated. 
WDYT?

**Comment by jansorg** [comment]
@ahtrotta Should `defaultFilter` only update the `default` flag or should it also update `state` and `filterName`? If it's the latter, what's the difference to `saveFilter`? Wouldn't `saveFilter` be enough to update the `defaultFilter` property?

**Comment by ahtrotta** [comment]
@jansorg, I didn't think about the fact that you can't import `AppMapFilter` into JetBrains as we do in VS Code, so I'll make the frontend create and save a default filter if `savedFilters` is an empty array.

**Comment by ahtrotta** [comment]
@jansorg `defaultFilter` should only update the `default` flag

**Comment by ahtrotta** [comment]
I noticed in your draft PR that when you save a filter you [automatically set it as default](https://github.com/getappmap/appmap-intellij-plugin/pull/313/files#diff-7b9f70c10fe5bce98ecd82a7ee675957687b3d968fe7333a153c2be57b97840fR82), but we don't want to do that, we just want to save the filter as-is. Also, if the filter already exists in the saved filters (just check the `filterName`) then we want to overwrite the old filter with the new one.

**Comment by jansorg** [comment]
@ahtrotta Thanks! I'll fix that when the updated components are available (i.e. with the change to  manage the default filter inside the webview)

**Comment by ahtrotta** [comment]
Oh yeah! I forgot to tell you that they're available as of today, version 2.52.0 of `@appland/components`.
