### ISSUE TITLE
The latest Java agent jar is downloaded upon every plugin startup

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#287]
Currently the plugin bundles the Java agent jar within the plugin zip. This means that it will progressively go out of date for users who install the plugin once but never update it. 

Instead, we would like the plugin to always download the latest Jar from the official location (if a newer one exists) upon each plugin startup.

The plugin should be added to the user's home directory under a `.appmap/lib/java` sub-folder on Linux and Mac, and the equivalent on Windows. 

The agent jar should also be saved without version numbers to predictably easy to find by our various tools and code. The name should be `appmap.jar`. Therefore the full path of where the jar should be saved would be `~/.appmap/lib/java/appmap.jar`. It should be saved with a versioned file name, and symlinked as `appmap.jar` to prevent changes to existing projects or run configurations. If symlinking fails (e.g. on Windows) then we should ensure that the latest jar file gets saved as `appmap.jar` regardless.

**Comment by brikelly** [comment]
@jansorg yes, but my comments in the issue above should address that (by placing it into the user's home directory), no?

**Comment by kgilpin** [comment]
I think you can find JAR version in the Manifest. Then you can easily determine if a new version of the JAR needs to be fetched
