### ISSUE TITLE
PyCharm installer mangles the console output

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#288]
When installing within a Python project (I used Misago) in PyCharm, the console used for the installer CLI has messy and unreadable text breaks:

![Image](https://github.com/getappmap/appmap-intellij-plugin/assets/573108/cdd11dd4-6d67-45c6-865c-0fc841aa5433)

**Comment by brikelly** [comment]
@jansorg this issue from June looks identical to the issue we discovered recently. Do you have any idea why it would have regressed?

**Comment by jansorg** [comment]
@brikelly could you link the other issue, please?
This issue is about garbled output, the only other issue I know was about a json parsing error in the pycharm console.

**Comment by brikelly** [comment]
The other issue is this one: https://github.com/getappmap/appmap-js/issues/1308
