### ISSUE TITLE
"Install AppMap Agent" has a green checkmark in supported Java projects

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#298]
Currently, the IntelliJ extension creates an `appmap.yml` in the project only when the user first starts their app or tests with AppMap (via the custom Run Configurations). 

We are planning to use the presence of `appmap.yml` in a project as a definitive sign that the user has successfully installed AppMap there. Therefore, we want the IntelliJ plugin to create the `appmap.yml` when they instead click this button to launch the "Install AppMap Agent" action:

![Image](https://github.com/getappmap/appmap-intellij-plugin/assets/573108/93b804c1-f0f9-4a25-8937-83ac2608ba32)

**Comment by jansorg** [comment]
- for Java only
- create for all Java modules if none was found
