### ISSUE TITLE
"Runtime Analysis panel" should display a tree

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#328]
![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/af4487c4-5a7c-4b90-b124-aec950f9dc90)

**Comment by dustinbyrne** [comment]
We need a written specification for this feature

**Comment by dustinbyrne** [comment]
The overall structure of the tree is as follows:
```
<Project name>
├── Findings
│   └── <Date bucket>
│       └── <Impact domain>
│           └── <Finding>
└── Failed tests
    └── <Failed test AppMap>
```

Date buckets are split as follows:
- Last 24 hours
- Last 7 days
- Last 30 days
- More than 30 days ago
- No date indicated

The date of a finding is found via the `eventsModifiedDate` property or `scopeModifiedDate` if the former is falsy. If both properties are falsy, fall back to `No date indicated`.

A "failed test" is an AppMap where the `metadata.test_status` property is set to `failed`.

**Comment by jansorg** [comment]
@dustinbyrne How's "<Project name>"  defined?

**Comment by jansorg** [comment]
@dustinbyrne VSCode displays a "Findings Table" node. Should it be always shown?

**Comment by jansorg** [comment]
@dustinbyrne I noticed that VSCode displays an additional group inside "Failed tests". Should I implement this, too? If I should, how's that group name found?

![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/20b788cf-52bd-40bf-9af1-005ef2febc00)

**Comment by kgilpin** [comment]
> @dustinbyrne If an Finding has "test_status: failed", should it be shown under both "Findings" and also "Failed tests" or only in the latter? VSCode seems to show it in both groups.

If a test has failed, it's optional for Findings on that AppMap to appear. It's not a big deal if it's in both places though.
