### ISSUE TITLE
Findings are classified by time

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#333]
In VS Code, we've added this time-based listing that puts older findings into their own section:

![Image](https://user-images.githubusercontent.com/573108/256027501-a369e6b5-bb75-4b4c-8d91-90f0ff2453fa.png)

We need a similar implementation in JetBrains.

**Comment by dustinbyrne** [comment]
Needs spec

**Comment by dustinbyrne** [comment]
This looks to be a duplicate of https://github.com/getappmap/appmap-intellij-plugin/issues/328
