### ISSUE TITLE
"Beachball" issues where the editor hangs

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#365]
User is getting a beachball when clicking around in the instructions view - need their IDEA log file.

**Comment by jansorg** [comment]
@brikelly The log file is available at `Help > Show log in Finder". After terminating/restarting the IDE, I'd need idea.log and idea.1.log to investigate this issue.

**Comment by jansorg** [comment]
@brikelly Even better would be `Help > Collect Log and Diagnostic Datat`, but the result zip should not be shared in public.

**Comment by jansorg** [comment]
Fixed by https://github.com/getappmap/appmap-intellij-plugin/pull/376
