### ISSUE TITLE
appmap.yml must not be overridden with new config setup

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#385]
appmap.yml seems to be overwritten when "Run with AppMap" is launched.

**Comment by brikelly** [comment]
@jansorg this still seems to be a problem. If I make changes to `appmap.yml`, they disappear after I choose "Start with AppMap".

**Comment by jansorg** [comment]
@brikelly Could you clarify which changes you made to the appmap.yml file, which were removed?

**Comment by brikelly** [comment]
@jansorg here's a Loom showing the issue: https://www.loom.com/share/506a906965f641e4b13dd1090b67daf2?sid=d5cbc802-bc9f-457c-8f29-01a2c9da205c
