### ISSUE TITLE
Findings should always be enabled if the user is signed in

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#388]
The experimental setting should be removed

**Comment by kgilpin** [comment]
@jansorg do you think that manual QA will be needed for this update?

**Comment by jansorg** [comment]
@kgilpin That would be useful. Because something is removed, it's not possible to test well with instructions ;) But the general testing of the plugin onboarding should cover all of it (i.e. installing plugin for the first time, opening a new project, signing in to the AppMap server, record AppMaps).
