### ISSUE TITLE
Better determination of when `Runtime Analysis` is marked as complete

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#396]
Right now the Analysis step goes green if someone simply clicks on it, even if there are no maps present.

Instead, we would like it to turn green only if:

The user clicks on that step, AND
There are maps in the project, AND
Those maps have been scanned (regardless of any flaws being discovered)

VS Code implementation (which should be followed) 
is here: https://github.com/getappmap/vscode-appland/pull/829

**Comment by jansorg** [comment]
@ahtrotta @brikelly I don't fully understand when/how this should be updated.
https://github.com/getappmap/appmap-intellij-plugin/pull/375 changed the update of the step to adapt to VSCode. To my knowledge, the VSCode plugin sets the step as checked when it's opened for the first time. If that's wrong, what exactly does VSCode implement?

**Comment by brikelly** [comment]
I think we can park this for now. It's not a huge issue and there are more important issues to address in the meantime.

**Comment by brikelly** [comment]
@jansorg we recently made these changes in VS Code and we would like JetBrains to follow them: https://github.com/getappmap/vscode-appland/pull/829

**Comment by jansorg** [comment]
@brikelly @ahtrotta 
>  The user clicks on that step
Is that a click on the "Next step" inside the webview panel leading to "Runtime Analysis" or a click on "Runtime Analysis" in the side panel? According to the VSCode plugin's PR it's just the former. Is this correct?

The PR seems to add another condition: "AppMaps have been opened". Should I do this as well?
https://github.com/getappmap/vscode-appland/pull/829/files#diff-da6cbc05619475bba27a9fb509cb05128dcfa31ce550df4135b87991066d3f8eR145

> Those maps have been scanned
As far as I understand this means: "If there's at least one appmap-findings.json` file in the workspace (empty or not), correct?

**Comment by brikelly** [comment]
@jansorg some answers:

1. It's a click on the Runtime Analysis step in the instructions sequence, not on the analysis side panel.
2. Yes, maps should be opened as well, good catch.
3. That's correct, yes.
