### ISSUE TITLE
Remove OpenAPI from onboarding flow

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#402]
Please remove the `Generate OpenAPI` page from the onboarding instructions. You'll need to update `@appland/components` to most recent version for this change.

![Image](https://github.com/getappmap/appmap-intellij-plugin/assets/45714532/79e495db-c1a1-43fd-948d-a991e2111895)

**Comment by jansorg** [comment]
Testing:

The webview part can't be tested with our JUnit tests. A tester has to ensure that
- the install instructions webview doesn't show the OpenAPI page anymore
- the action to manually create OpenAPI is still working as before (Tools > AppMap > Generate OpenAPI)
