### ISSUE TITLE
IntelliJ defaults to tmp for finding AppMaps

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#408]
This would be the case regardless of whether the project is Maven or Gradle-based. We want to make tmp/appmap consistent as the default AppMap folder.

This should be done only after https://github.com/getappmap/appmap-java/issues/210 is released.

**Comment by brikelly** [comment]
Thanks @jansorg . We plan to release all the changes for `tmp` (the JB plugin, the Java agent, and both Maven/Gradle plugins) at the end of the week because they all need to go out the door together and we can't predict how long their marketplace approval will take.

**Comment by jansorg** [comment]
Because the JetBrains plugin downloads the latest release of the agent, it must be available on GitHub when the plugin is available to users. It would also be good to test the build of the PR‘s plugin branch together with the updated agent.

**Comment by jansorg** [comment]
My guess is that the plugin could use any version of the agent, because it‘s always passing the path to the agent when tests are executed. But testing both would still be required for good qa.

**Comment by brikelly** [comment]
Yes we will release the agent to GitHub first (say, Friday afternoon) at the same time that we release the plugin to the marketplace for approval. By the time it's approved, we'll have made the new agent live on GitHub & maven central.
