### ISSUE TITLE
AppMap CLI process could be terminated in a better way

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#411]
The service, which keeps track of running AppMap CLI processes, is terminating them when the project is closed.
It currently removes the process entry from the internal map and then terminates the 2 linked AppMap processes. 
This doesn't support the following two cases well:
- AppMap processes crash (e.g. because of a bug). In this case the process is not detected as terminated and no restart is attempted (if we'd like to do this)
- Processes, which don't terminate as expected, can't be detected.

**Comment by kgilpin** [comment]
There is a restart with back off in VSCode extension
