### ISSUE TITLE
Telemetry for findings should be removed

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#424]
Specifically, this blob should be removed from the plugin: https://github.com/getappmap/appmap-intellij-plugin/blob/17fa0bd14f1d5e7a218bad461c56d7b2ce5baadc/plugin-core/src/main/java/appland/webviews/findings/FindingsOverviewEditor.java#L55-L87

**Comment by kgilpin** [comment]
You're just going to remove that one file? Or you're going to do a telemetry cleanup like in VSCode?

There is already a story for that BTW.
