### ISSUE TITLE
Users see a notification box when they create their first map

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#432]
Similar to these types of message boxes:
![Image](https://user-images.githubusercontent.com/573108/268423788-1c1bda4a-39bf-4f79-adb3-568925adc193.png)

We need to show a similar type of notification message when a user creates their very first map after installing the plugin for the first time, and only show it that one time. The purpose is to help guide new users towards their AppMaps, because they might not notice that they've been created or know how to even open them.

The text of the notification should be:
"You've created your first AppMap! Congratulations."
There should be one button as a primary action, colored in blue as above, with the text "Open your new AppMap"

This notification should only be seen at most once on a user's system.

**Comment by jansorg** [comment]
> This notification should only be seen at most once on a user's system.
@brikelly This requirement doesn't fit with the way settings are handled. What's possible is to show only once for the installation of an IDE. For example, a user using IntelliJ Ultimate would see it only once on a system for IntelliJ Ultimate. But if the same user has installed another IDE, e.g. RubyMine, then the notification would be displayed once for RubyMine, too.
Would this be good enough?

**Comment by brikelly** [comment]
> > This notification should only be seen at most once on a user's system.
> 
> 
> 
> @brikelly This requirement doesn't fit with the way settings are handled. What's possible is to show only once for the installation of an IDE. For example, a user using IntelliJ Ultimate would see it only once on a system for IntelliJ Ultimate. But if the same user has installed another IDE, e.g. RubyMine, then the notification would be displayed once for RubyMine, too.
> 
> Would this be good enough?

Yes, absolutely fine to do it this way and show it once per installation.
