### ISSUE TITLE
The Analysis step should lead the user to the Findings Overview, not the Problems tab

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#433]
Instead of directing users to the Problems tab to view problems:
![Image](https://user-images.githubusercontent.com/573108/268465872-274fbb22-12ed-449b-9ae6-62f29fc29812.png)

That button should go to the Findings Overview instead:
![Image](https://github.com/getappmap/vscode-appland/assets/573108/d384a31b-44c4-483d-873b-f1671cc06359)

**Comment by jansorg** [comment]
## Testing
- The "findings overview" webview must be opened when the button "Open problems tab" is clicked in the "Runtime Analysis" page of the installation instructions webview.
