### ISSUE TITLE
PyCharm automated install creates an appmap.yml too early

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#451]
PyCharm 2023.2.1 (Community Edition), MacOS, plugin v.0.50.0

With a fresh PyCharm install, I installed the AppMap plugin from the marketplace, installed AppMap into [this](https://github.com/jainamoswal/Flask-Example) freshly-cloned project. 

There was no `appmap.yml` in the project before I ran the installer, but the installer reported the following:

```
/Users/brikelly/Library/Caches/JetBrains/appland-plugin/appmap/3.96.3/appmap-macos-arm64 install -d /Users/brikelly/code/demos/Flask-Example-Sep-19
Installing AppMap agent for Flask-Example-Sep-19...
? AppMap is about to be installed. Confirm the details below.
  Project type: pip
  Project directory: /Users/brikelly/code/demos/Flask-Example-Sep-19
  Git remote: origin    git@github.com:jainamoswal/Flask-Example.git (fetch)
  Python version: 3.11.4
  Python package directory: /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11

  Is this correct? (Y/n) ? An appmap.yml configuration file already exists. How should the conflict be resolved? (Use arrow keys)
❯ Use existing 
  Overwrite 
```

The `appmap.yml` file that was auto-generated contained the following content:

```
appmap_dir: tmp/appmap
language: python
name: Flask-Example-Sep-19
packages:
  - path: modules
```

The presence of this yml file is used by the installer to determine success, so the "Install AppMap Agent" step went green before I'd finished running the installer.

**Comment by jansorg** [comment]
@brikelly As far as I can tell the CLI installer is creating the file before prompting about the conflict. The JetBrains plugin is only creating appmap.yml for Java projects.

Just executing the CLI on my macOS displayed the message about the conflict, so it seems to create the file on its own.

Please try the following. If it fails, then it's not a problem with the plugin, but with https://github.com/getappmap/appmap-js.
```bash
cd /Users/brikelly/code/demos/Flask-Example-Sep-19
rm -f appmap.yml
/Users/brikelly/Library/Caches/JetBrains/appland-plugin/appmap/3.96.3/appmap-macos-arm64 install -d /Users/brikelly/code/demos/Flask-Example-Sep-19
```

**Comment by brikelly** [comment]
Hi @jansorg, the command line test which you suggested proves that it is a problem with appmap-js, not the IDE plugin. I will open a new issue in that repo.
