### ISSUE TITLE
Clicking on a code object (SQL/API) in the code objects view does not select the location in the Dependency Map where that object is used.

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-intellij-plugin#458]
Clicking on a code object (SQL/API) in the code objects view does not select the location in the Dependency Map where that object is used.

[Here is a video showing the issue](https://www.loom.com/share/53bcb74832224bb0b4c455b9583e7911)

This map is the one used in the demo video.  
[New_Group_Creation.appmap.json.zip](https://github.com/getappmap/appmap-intellij-plugin/files/12742589/New_Group_Creation.appmap.json.zip)

When clicking on a SQL query or an API request, the code editor should open up the relevant appmap and select the location on the dependency map where that code object is used.  Currently in Intellij -the appmap is opened but the code object is not selected in the viewer.  

See this example from VS Code showing the expected outcome.  

<img width="1649" alt="Screenshot 2023-09-27 at 3 26 12 PM" src="https://github.com/getappmap/appmap-intellij-plugin/assets/511733/54d71d49-37d5-4bfc-a75e-488a4b68385b">

**Comment by brikelly** [comment]
@jansorg This is actually more important than the other IntelliJ tasks we discussed today - can we prioritize this one at the top of your to-do list please? Thanks!

**Comment by brikelly** [comment]
And if you need the source code to the app, this is it I believe: https://github.com/finos/waltz
