### ISSUE TITLE
AppMaps can be deleted similar to how VS Code allows

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#465]
In VS Code, single AppMaps can be deleted by clicking the "trashcan" icon which appears next to them when hovering. Doing so removes it from the filesystem and closes the file if it's open in the viewer.
![Image](https://github.com/getappmap/appmap-intellij-plugin/assets/573108/47e8f752-4142-428a-b3bc-de40685f59af)
This should be implemented in an identical manner to VS Code.

In VS Code you can also use the Command Palette to delete all AppMaps with one action.
![Image](https://github.com/getappmap/appmap-intellij-plugin/assets/573108/8ed3d9bc-c851-4f82-94e5-353d0c7163d5)
This should be implemented using the `Tools` -> `AppMap` sub menu, where we can offer a menu option to `Delete All AppMaps`

**Comment by kgilpin** [comment]
`Delete All AppMaps` deletes *all* AppMaps. 

There is a right click context menu to delete folder contents.
