### ISSUE TITLE
Inconsistent naming for remote recording appmaps

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#477]
I did three remote recordings in `spring-petclinic` and I named them `first recording`, `second recording`, and `third recording`. The name of the appmap file looks fine, but I got three different naming patterns in the appmap sidebar:

![Image](https://github.com/getappmap/appmap-intellij-plugin/assets/45714532/23c89aa7-6713-45ba-9591-9903b52cd7bb)

**Comment by jansorg** [comment]
The plugin is always updating property `metadata.name` of the new AppMap JSON. 
But because the JSON data is streamed to disk using extension `.appmap.json` it's possible that the indexer picks up the name contained in the AppMap (e.g. `Remote Recording - 13:28:49.606`).
