### ISSUE TITLE
Integrate the help desk frontend

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-intellij-plugin#527]
A new frontend component exposes the Chat API.
https://github.com/getappmap/appmap-js/blob/main/packages/components/src/pages/Chat.vue

In VSCode, the frontend application is implemented like so:
https://github.com/getappmap/vscode-appland/blob/feat/chat/web/src/aiHelp.js

The component takes three props:
- `apiKey`, the user's API key from sign in
- `apiUrl`, the URL of the API server (`https://api.getappmap.com` by default, consider making this a configuration property)
- `suggestions`, an array of suggestion prompts. These are not yet finalized, but feel free to copy what's in VSCode as a placeholder. The shape of the `suggestion` elements is described here: https://github.com/getappmap/appmap-js/blob/main/packages/components/src/components/chat/SuggestionGrid.vue#L21-L25

The instruction frontend will require an additional prop, `displayAiHelp` set to true.
https://github.com/getappmap/vscode-appland/blob/feat/chat/web/src/installGuideView.js#L26

When the user clicks the button to ask AppMap AI, an `ai-help` event is emitted, and should be handled to open the new help desk webview.
https://github.com/getappmap/vscode-appland/blob/feat/chat/web/src/installGuideView.js#L105-L107

That's it. There may be some bundling configuration where `socket.io-client` needs a webpack alias to the correct artifact. This is `esbuild`, but the solution is similar: https://github.com/getappmap/vscode-appland/blob/develop/tsup.config.ts#L49

**Comment by jansorg** [comment]
AFAIK this was superseded by the Navie webview.
