### ISSUE TITLE
Creation of appmap.yml for multi-module Gradle projects is not handled well

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-intellij-plugin#546]
In a test setup with 2x sprint-petclinic the appmap.yml file was created in the wrong directory.

Problems and setups to look at:
- [x] Make sure that the working directory of AppMap CLI processes is set to the parent directory of `appmap.yml`
- [x] Make sure that even for Java processes launched in a IDE sub-module a top-level appmap.yml file is used (if it's the valid appmap.yml file for the module structure)
- [ ] Make sure that the AppMap Java agent does not depend on the working directory of its JVM parent process

Related issues and PRs:
- https://github.com/getappmap/appmap-java/issues/271
- https://github.com/getappmap/appmap-intellij-plugin/pull/656

**Comment by kgilpin** [comment]
Wouldn’t it be in the working directory of the process?

Please share more details.
