### ISSUE TITLE
Instructions are updated to include Navie

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-intellij-plugin#591]
The instructions pages should be:
- Add AppMap to your project
- Record AppMaps
- Ask AppMap Navie AI

"Explore AppMaps" and "Runtime analysis" should be removed.

"Ask AppMap Navie AI" simply opens the Navie UI and checks off the step.

**Comment by jansorg** [comment]
@dustinbyrne I must also update the install guide webview to the latest version, right?

The "Explore AppMaps" page is currently also shown by the "You've created your first AppMap" notification. What should button "View your AppMaps" of this notification show instead?

The plugin also tracked if the used opened page "Runtime Analysis" and passed this as `investigatedFindings` project metadata property to the install guide webview. I suppose that this should be dropped, too?
