### ISSUE TITLE
`NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "appMaps" is null`

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#620]
```
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "appMaps" is null
               at appland.toolwindow.appmap.nodes.RootNode.getFiles(RootNode.java:64)
```

**Comment by jansorg** [comment]
This issue seems like https://github.com/getappmap/appmap-intellij-plugin/commit/9ae8a8ecfde5f18a2ad0630f977cc96971c7d5cf, I'm not sure how a NullPointerException could be caused with the current code.

**Comment by jansorg** [comment]
Closing as it's a duplicate and I don't see any other way how this could happen with the current version.
