### ISSUE TITLE
Add a status indicator to display the status of external resources

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-intellij-plugin#625]
- Indicate the status of the JAR file (current version, up to date/failed to update) and where to find logs
- Indicate the status of the CLI binaries (current version, up to date/failed to update) and where to find logs

**Comment by jansorg** [comment]
A webview is a heavy component (memory, cpu and bundled webview assets). IMHO a native integration using Java Swing would be better. 

I would suggest to show at least the following:
- State of signed in
- State of the JavaAgent (downloaded version or error if it failed)
- State of the AppMap Indexer (downloaded version or error if it failed)
- State of the AppMap Scanner (downloaded version or error if it failed)

Here's what GitHub Copilot is displaying when you click its icon in the statusbar:
![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/c30a3708-b2f1-4d96-95c7-e2a89334c0a5)
