### ISSUE TITLE
Inconsistency in JetBrains when finding maps in recursive subdirectories

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-intellij-plugin#631]
Using Intellij version:
```
IntelliJ IDEA 2023.1.6 (Community Edition)
Build #IC-231.9414.13, built on February 14, 2024
Runtime version: 17.0.10+10-b829.26 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    idea.plugin.protoeditor (231.9225.5)
    Docker (231.9414.12)
    org.jetbrains.kotlin (231-1.9.22-release-704-IJ8109.175)
    appland.appmap (0.60.0)

Kotlin: 231-1.9.22-release-704-IJ8109.175
```

It looks like the AppMap plugin searches recursively for tmp/appmap in project subdirectories.  But currently Navie will not be able to find the maps unless they are in tmp/appmap in the root of the project.  

In this screenshot you can see that maps exist and are in the navie window list but the alert says it can't find the maps. 
![Screenshot 2024-03-21 at 9 38 00 AM (1)](https://github.com/getappmap/appmap-intellij-plugin/assets/511733/af98a1d6-350a-45b8-98bf-edb3bc2e148b)

Asking navie a question, the response will be as if no maps exist. 

<img width="1248" alt="Screenshot 2024-03-21 at 9 43 07 AM" src="https://github.com/getappmap/appmap-intellij-plugin/assets/511733/5d57bb93-2755-42e9-9587-63f63ec533b4">

In this Loom you'll see that the maps are in ./waltz-web/target/tmp/appmap, and they are listed in the sidebar, so the plugin can find them but Navie can not.  

https://www.loom.com/share/a78a281bdf5449cd98ee1c71d2209801

**Comment by jansorg** [comment]
@petecheslock What's the content of your appmap.yml file?
The plugin shows all AppMaps, which have matching metadata, i.e. which have been processed by the AppMap indexer.
How did you create the AppMaps located in the `waltz-web` subdirectory?

**Comment by petecheslock** [comment]
Hey @jansorg  - here is my `appmap.yml`

```
# This is the AppMap configuration file.
# For full documentation of this file for Java programs, see:
# https://appland.com/docs/reference/appmap-java.html#configuration
name: waltz
packages:
  - path: org.finos.waltz
# appmap-java init looks for source packages in src/main/java.
# This folder was not found in your project, so no packages were auto-detected.
# You can add your source packages by replacing the line above with lines like this:
# packages:
# - path: com.mycorp.pkg
# - path: org.otherstuff.pkg
```

Basically the default created one.  

In this project i started the postgres backend in docker `docker compose up -d postgres` and then i added appmap to my `pom.xml`

<img width="586" alt="Screenshot 2024-04-02 at 10 14 59 AM" src="https://github.com/getappmap/appmap-intellij-plugin/assets/511733/c07d6e70-798e-4ed2-a19d-8eb69b48ae17">

Then using maven ran the clean/test commands to run the tests and generate maps

<img width="502" alt="Screenshot 2024-04-02 at 10 13 51 AM" src="https://github.com/getappmap/appmap-intellij-plugin/assets/511733/5cf1ece2-1f2a-4ba6-bd77-5ac1e0a0b06d">

You'll see maps in the subprojects directories under <subproject>/tmp/appmap

<img width="1346" alt="Screenshot 2024-04-02 at 10 21 37 AM" src="https://github.com/getappmap/appmap-intellij-plugin/assets/511733/02eee46d-650c-4d19-8f20-e4d96967632d">

This issue mainly shows up with Navie, which looks into `./tmp/appmap` and thus would see no appmaps, yet the plugin DOES find all the maps correctly..

```
$ find . -name \*appmap.json | wc -l
     881
```

But navie can't find them.

<img width="1492" alt="Screenshot 2024-04-02 at 10 23 37 AM" src="https://github.com/getappmap/appmap-intellij-plugin/assets/511733/2951d2b7-83f9-4d81-ab0a-17c7f59ff01f">

**Comment by jansorg** [comment]
I believe that this issue has been fixed by the latest changes, especially the change to improve support for Maven multi-module builds.
@petecheslock Could you test this again and close this issue if everything is okay now, please?

**Comment by kgilpin** [comment]
@petecheslock @jansorg does the “generated” appmap yml not contain the language field? This is required and should be there.

**Comment by kgilpin** [comment]
Also I’m glad to see that you have just one appmap yml in the project root. This is the way it should be done.

**Comment by jansorg** [comment]
@kgilpin No, an appmap.yml generated by the JetBrains plugin does not set a language field. I wasn't aware that it exists. Is this property and the possible values documented somewhere?
At this time, properties `name`, `appmap_dir` and `packages` are set.

**Comment by jansorg** [comment]
@petecheslock AFAIK this should all be fixed now with today's new version. Do you mind to test this again and reopen if if's still happening? Thanks!

**Comment by petecheslock** [comment]
Great thanks - what version should I make sure i'm on to confirm things are working? I guess alternatively i can build the plugin off the mainline and test with that as well.

**Comment by petecheslock** [comment]
Ok - i built the plugin off of mainline develop branch and basically when there is an appmap.yml in any of my project subdirectories then things get processed correctly and Navie is able to see the maps.  If that is the behavior we are expecting then sounds like we are all set.
