### ISSUE TITLE
Navie can be opened through an AppMap

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-intellij-plugin#640]
For the VS Code implementation, see this PR: https://github.com/getappmap/vscode-appland/pull/920

Handle messages and props related to [this PR](https://github.com/getappmap/appmap-js/pull/1636) so that users can open Navie from within an AppMap and ask about it.

### New prop

`appmapFsPath`: Pass this prop to the AppMap webview when opening. It is the file system path of the AppMap. This is required for this feature to work correctly.

### New message

`ask-navie-about-map`: This is emitted when a user clicks on the `Ask Navie` button in an AppMap. It will have one parameter `mapFsPath`, which is the file system path of the appmap. To handle this message:

1. Read the AppMap data from the specified file path.
2. Open Navie, passing the props `targetAppmapData` and `targetAppmapFsPath`. `targetAppmapData` is the AppMap data that was just read from the file and `targetAppmapFsPath` is `mapFsPath`.

### New props

`targetAppmapData`: This is an optional prop that should be set when handling the `ask-navie-about-map` event from above. It is the raw AppMap data of the target AppMap.

`targetAppmapFsPath`: This is an optional prop that should be set when handling the `ask-navie-about-map` event from above. It is the file system path of the target AppMap.

**Comment by jansorg** [comment]
Is the data for `targetAppmapData` the raw AppMap data or should the additional properties like `findings` be attached here, too?

**Comment by ahtrotta** [comment]
Just the raw AppMap data
