### ISSUE TITLE
Integrate the Navie context panel

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-intellij-plugin#677]
- `@appland/components` is updated in the Navie view
  - A new event is emitted, `open-location`, which indicates the user has requested to open contextual information in the editor, directly from the source.
  - The first (and only) argument passed along with this event is the location. This is a path (either relative or absolute), with an optional starting line number and optional ending line number in the following format: `path:startingLine-endingLine`. Below are all valid examples:
  ```
  C:\\Users\\example.appmap.json:35
  C:\\Users\\Default\\MyProject\\example.rb:35-99
  MyProject/example.rb:35-99
  MyProject/example.appmap.json
  /home/user/dev/appmap/example.java:56
  ```
  - If the path is an `appmap.json`, the starting line is actually an event ID. The [AppMap should be opened with the following state](https://github.com/getappmap/appmap-intellij-plugin/blob/develop/appland/webview.js#L34), where `${startLine} is substituted with the starting line or event ID.
   ```json
   {
      "currentView": "viewSequence",
      "selectedObject": "event:${startLine}"
    }
    ```
  - Otherwise, the location should be opened as a text document.
  - If a start and end line are provided, once open, the document should scroll to the range of text provided.
  - If only a start line is provided, the document should scroll to the start line
  - If neither are provided, the document simply opens and no scrolling takes place.
- ~Keep in mind, if the location is a relative path, it may match more than one module. For now, simply select the first match. We'll fix this in a future revision.~
  - A `directory` property will indicate where the file is located. It may still need to be searched for (i.e., a partial path), though the `directory` will identify the correct root directory. See [this source](https://github.com/getappmap/appmap-js/blob/a51cb16f8f81a240d7662ff23ff2a175d1a8c39b/packages/navie/src/context.ts#L48-L54) for more information. 

Sample context data is available here:
https://raw.githubusercontent.com/getappmap/appmap-js/main/packages/components/src/stories/data/navie_context.json

**Comment by jansorg** [comment]
@dustinbyrne Are lines 1-based or 0-based?

**Comment by jansorg** [comment]
@dustinbyrne Is VSCode displaying an error if no file for a given relative path was found?

**Comment by kgilpin** [comment]
Context item should have a directory; this may be something we can fix now.

The file may still need to be located though, because the Java agent can’t
always determine full file paths.

**Comment by dustinbyrne** [comment]
> @dustinbyrne Are lines 1-based or 0-based? Update: 1-based, it seems.

This is correct, they are 1-based.

Regarding the location of relative paths, a `directory` will indicate the root directory of a particular location. As Kevin mentioned, some paths may still be partial, but they should be able to be located within the directory given.

https://github.com/getappmap/appmap-js/blob/a51cb16f8f81a240d7662ff23ff2a175d1a8c39b/packages/navie/src/context.ts#L48-L54

**Comment by dustinbyrne** [comment]
> @dustinbyrne Is VSCode displaying an error if no file for a given relative path was found?

At the moment nothing happens.
