### ISSUE TITLE
extra path entries in `appmap.yml`

### ISSUE THREAD

**Issue by apotterri** [getappmap/appmap-intellij-plugin#690]
Sometimes there are `path` entries added for non-application packages.

For example, the plugin generates this `appmap.yml` for waltz:
```
name: "waltz"
appmap_dir: "tmp/appmap"
packages:
- path: "app-group.add-aliases"
- path: "clients.c1.sc1"
- path: "licence.finos"
- path: "licence.spdx"
- path: "lineage"
- path: "liquibase"
- path: "measurable-ratings.edit-ratings"
- path: "org.finos.waltz.common"
- path: "org.finos.waltz.data"
- path: "org.finos.waltz.jobs"
- path: "org.finos.waltz.model"
- path: "org.finos.waltz.service"
- path: "org.finos.waltz.web"
- path: "report-grid.create-grid"
- path: "spark.template.freemarker"
- path: "static"
- path: "taxonomies"
- path: "user.registration"
```
It should really have no more than
```
- path: "org.finos.waltz.common"
- path: "org.finos.waltz.data"
- path: "org.finos.waltz.jobs"
- path: "org.finos.waltz.model"
- path: "org.finos.waltz.service"
- path: "org.finos.waltz.web"
```
and, ideally, even these would be collapsed to their common prefix, i.e. `- path: "org.finos.waltz"`.

**Comment by jansorg** [comment]
Currently, the package list also includes packages contained in resource folders. Filtering to only allow packages located in source code folders should be possible.

I don't think we could collapse `a.b.c.*` itno `a.b.c` (e.g. `org.finos.waltz.*` into `org.finos.waltz`) because there may be projects which share a common package prefix with others.

**Comment by apotterri** [comment]
Ok, I'll look at filtering out resource folders.

Re collapsing packages: my example was wrong. We wouldn't want to collapse the `path` entries in this case. We'd only want to do it if they also contained the common prefix itself, e.g. `org.finos`, or `org.finos.waltz`, indicating that there are classes in that package.

**Comment by jansorg** [comment]
@apotterri Starting point to filter the packages would be `appland.execution.AppMapJavaPackageConfig#findTopLevelPackages` and probably `appland.execution.AppMapJavaPackageConfig#collectSourceRootsWithDependencies`.
I haven't worked with the Java project model (source folders, resource folders, etc), but these methods seem most promising to me: 
`ModuleRootManager.getInstance(module).getContentEntries()[...].getSource*()``.

**Comment by kgilpin** [comment]
What answer do you get if you ask Navie how to implement this?
