### ISSUE TITLE
Navie conversation is destroyed when a link is clicked

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/appmap-intellij-plugin#755]
When a Navie response contains a link, the link opens the destination in an external browser AND in an embedded browser. The embedded browser would be handy but in it's current form it destroys data.  Once the embeddee browser opens my Navie conversation is over and inaccessible because there is no 'back' functionality. The fact that there is no conversational history compounds the loss... once a link is clicked, the conversation is effectively over.

![image](https://github.com/user-attachments/assets/05316ac7-9c89-46bf-a748-549969deecb1)

**Comment by dustinbyrne** [comment]
See https://github.com/getappmap/appmap-intellij-plugin/issues/753

**Comment by Daniel-Warner-X** [comment]
dupe
